### ISSUE TITLE
Issue with reference provided for km values

### ISSUE THREAD

**Issue by DeepaMahm** [matthiaskoenig/brendapy#11]
Test case: ec = '2.6.1.42'
organism  = 'Homo sapiens'
protein_id = 5
Output returned:
```
('KM',
              [{'data': '2.4 {2-oxoglutarate}', 'refs': [4, 5]},
               {'data': '1.7 {2-oxoglutarate}', 'refs': [4, 5, 17, 63]},
               {'data': '1 {2-oxoglutarate}', 'refs': [4, 5, 6, 17]},
               {'data': '0.06 {', 'refs': [5]},
               {'data': '0.17 {', 'refs': [5]},
               {'data': '0.26 {glyoxylate}', 'refs': [5]},
               {'data': '0.41 {2-Oxohexanoate}', 'refs': [5]},
               {'data': '0.6 {beta-chloro-L-alanine}', 'refs': [5]},
               {'data': '0.21 {2-Oxoisohexanoate}', 'refs': [5]},
               {'data': '0.09 {', 'refs': [5]},
               {'data': '0.11 {glyoxylate}', 'refs': [5]},
```
Multiple references are mapped for single `Km` value
e.g.
  {'data': '1.7 {2-oxoglutarate}', 'refs': [4, 5, 17, 63]}

Info provided on database:
https://www.brenda-enzymes.org/enzyme.php?ecno=2.6.1.42&Suchword=&reference=&UniProtAcc=&organism%5B%5D=Homo+sapiens&show_tm=0

Only single reference is provided for each km value in the database.

Please check this .

**Comment by matthiaskoenig** [comment]
References are now correct, but it is very difficult to get the subset of references which are associated with a given protein for a KM value.

**Comment by DeepaMahm** [comment]
Hi @matthiaskoenig 

There is still some issue with the reference and comments of Km value. Multiple references and multiple comment lines are mapped to single Km value. On the webpage, each Km value is mapped to one reference and one comment. Kindly look into this.

Test case: ec = '2.6.1.42'
organism = 'Homo sapiens'
protein_id = 5
Output returned:
```
             {'comment': '#4# pH 8.0, 25°C, substrate L-valine <23,40>; '
                           '#5,17# pH 8.0, 37°C, isoenzyme III, valine as '
                           'amino group donor <24>; #63# half transamination '
                           'reaction, pH 8.0, 90°C <96>',
                'data': '1.7 {2-oxoglutarate}',
                'refs': [23, 24, 40, 96],
                'substrate': '2-oxoglutarate',
                'units': 'mM',
                'value': 1.7}
```
