### ISSUE TITLE
brenda_download.txt - file not downloaded during installation

### ISSUE THREAD

**Issue by DeepaMahm** [matthiaskoenig/brendapy#25]
After installing `brendapy` via `pip install brendapy` , `brenda_download.txt` wasn't found in the resources folder.

I tried manually downloading it from the github link, 
https://github.com/matthiaskoenig/brendapy/blob/develop/brendapy/resources/brenda_download.txt. But I couldn't find the complete contents of the file.

I also tried to download the file from brenda- [downloads](https://www.brenda-enzymes.org/download_brenda_without_registration.php). 
There is a Unicode error while running brenda_parser.py using the input file(brenda_download.txt) downloaded from brenda. 
`return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4870: character maps to <undefined>`

**Comment by matthiaskoenig** [comment]
Hi @DeepaMahm,
this is related to #15 (my bandwidth quota was reached, so I have to host the file somewhere else, so basically a duplicate of that issue). I will fix this today latest tomorrow.

Best Matthias

**Comment by DeepaMahm** [comment]
Hi @matthiaskoenig 
Could you please let me know if this issue is fixed?

**Comment by DeepaMahm** [comment]
Hi @matthiaskoenig 
This error reported above is also resolved by using the solution posted [here](https://github.com/matthiaskoenig/brendapy/issues/29)

**Comment by matthiaskoenig** [comment]
@DeepaMahm Perfect. I thought it was a different issue.
