### ISSUE TITLE
Problem with ujson when installing via PIP

### ISSUE THREAD

**Issue by bilehtin** [matthiaskoenig/brendapy#37]
Hi @matthiaskoenig 
Thanks for this nice package. I hope I get to use it soon. I'm actually having a problem installing it via pip, specifically with ujson. It says

"ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly"
Would you know how to solve this? So far I tried to install without PEP517 but this didn't work either.

I'm pasting the whole traceback below

Thanks,
Birgitta
-------------------------------------------------------------------------------------------

computer:~ blehtinen$ pip install brendapy
Processing ./Library/Caches/pip/wheels/07/4e/60/5aaf253071c0064f28bf0fc4a928066ef114a230c585eb5ec8/brendapy-0.4.1-cp36-none-any.whl
Requirement already satisfied: pip>=19 in /anaconda3/lib/python3.6/site-packages (from brendapy) (20.0.2)
Processing ./Library/Caches/pip/wheels/a4/f5/cd/357e802aa4c8313bf7ee78aa89b9791cef93661ff112259520/Owlready2-0.23-cp36-none-any.whl
Collecting ujson>=1.35
  Using cached ujson-2.0.2.tar.gz (7.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: requests>=2.22 in /anaconda3/lib/python3.6/site-packages (from brendapy) (2.23.0)
Requirement already satisfied: pyparsing>=2.4.2 in /anaconda3/lib/python3.6/site-packages (from brendapy) (2.4.6)
Requirement already satisfied: pandas>=0.25 in /anaconda3/lib/python3.6/site-packages (from brendapy) (1.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.6/site-packages (from requests>=2.22->brendapy) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /anaconda3/lib/python3.6/site-packages (from requests>=2.22->brendapy) (2.6)
Requirement already satisfied: chardet<4,>=3.0.2 in /anaconda3/lib/python3.6/site-packages (from requests>=2.22->brendapy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /anaconda3/lib/python3.6/site-packages (from requests>=2.22->brendapy) (1.22)
Requirement already satisfied: numpy>=1.13.3 in /anaconda3/lib/python3.6/site-packages (from pandas>=0.25->brendapy) (1.14.2)
Requirement already satisfied: pytz>=2017.2 in /anaconda3/lib/python3.6/site-packages (from pandas>=0.25->brendapy) (2017.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /anaconda3/lib/python3.6/site-packages (from pandas>=0.25->brendapy) (2.6.1)
Requirement already satisfied: six>=1.5 in /anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas>=0.25->brendapy) (1.11.0)
Building wheels for collected packages: ujson
  Building wheel for ujson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /anaconda3/bin/python /anaconda3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/vm/mzshf8w54cx72nn346yhbyyh0000gn/T/tmppk6e_6_f
       cwd: /private/var/folders/vm/mzshf8w54cx72nn346yhbyyh0000gn/T/pip-install-ldxzrn89/ujson
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  creating build
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/deps
  creating build/temp.macosx-10.7-x86_64-3.6/deps/double-conversion
  creating build/temp.macosx-10.7-x86_64-3.6/deps/double-conversion/double-conversion
  creating build/temp.macosx-10.7-x86_64-3.6/lib
  creating build/temp.macosx-10.7-x86_64-3.6/python
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I./python -I./lib -I./deps/double-conversion/double-conversion -I/anaconda3/include/python3.6m -c ./deps/double-conversion/double-conversion/bignum.cc -o build/temp.macosx-10.7-x86_64-3.6/./deps/double-conversion/double-conversion/bignum.o -D_GNU_SOURCE
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly

**Comment by matthiaskoenig** [comment]
This is related to ujson and should be fixed in the upcoming release.
